version: "3.8"

services:
  cron:
    build:
      context: ..
      dockerfile: packages/cron/Dockerfile
    container_name: cron
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
